/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class frmIngrediente extends javax.swing.JFrame {

    /**
     * Creates new form frmIngrediente
     */
    public frmIngrediente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtValorRecolectado = new javax.swing.JTextField();
        txtCalidad = new javax.swing.JTextField();
        btnRecibirMoneda = new javax.swing.JButton();
        btnCancelarOperaciones = new javax.swing.JButton();
        btnServirProducto = new javax.swing.JButton();
        btnEntregarVuelto = new javax.swing.JButton();
        btnElegirIngrediente = new javax.swing.JButton();
        btnLeer = new javax.swing.JButton();
        btnEscribir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombre.setBackground(new java.awt.Color(204, 255, 255));

        txtValorRecolectado.setBackground(new java.awt.Color(204, 255, 255));
        txtValorRecolectado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorRecolectadoActionPerformed(evt);
            }
        });

        txtCalidad.setBackground(new java.awt.Color(204, 255, 255));

        btnRecibirMoneda.setBackground(new java.awt.Color(255, 153, 204));
        btnRecibirMoneda.setText("Recibir Moneda");
        btnRecibirMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibirMonedaActionPerformed(evt);
            }
        });

        btnCancelarOperaciones.setBackground(new java.awt.Color(255, 153, 204));
        btnCancelarOperaciones.setText("Cancelar Operaciones");
        btnCancelarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarOperacionesActionPerformed(evt);
            }
        });

        btnServirProducto.setBackground(new java.awt.Color(255, 153, 204));
        btnServirProducto.setText("Servir Producto");
        btnServirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServirProductoActionPerformed(evt);
            }
        });

        btnEntregarVuelto.setBackground(new java.awt.Color(255, 153, 204));
        btnEntregarVuelto.setText("Entregar Vuelto");
        btnEntregarVuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarVueltoActionPerformed(evt);
            }
        });

        btnElegirIngrediente.setBackground(new java.awt.Color(255, 153, 204));
        btnElegirIngrediente.setText("Elegir Ingrediente");
        btnElegirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirIngredienteActionPerformed(evt);
            }
        });

        btnLeer.setBackground(new java.awt.Color(102, 255, 102));
        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        btnEscribir.setBackground(new java.awt.Color(102, 255, 102));
        btnEscribir.setText("Escribir");
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor Recolectado");

        jLabel2.setText("Nombres");

        jLabel3.setText("Calidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addComponent(txtCalidad))
                            .addComponent(txtValorRecolectado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRecibirMoneda)
                                    .addComponent(btnLeer)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnServirProducto)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancelarOperaciones)
                                    .addComponent(btnEscribir)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnEntregarVuelto))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnElegirIngrediente)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorRecolectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeer)
                    .addComponent(btnEscribir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecibirMoneda)
                    .addComponent(btnCancelarOperaciones))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServirProducto)
                    .addComponent(btnEntregarVuelto))
                .addGap(18, 18, 18)
                .addComponent(btnElegirIngrediente)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Instanciar la clase Alumno
    CapaNegocio.Ingredientes ingredientes = new CapaNegocio.Ingredientes();
    private void txtValorRecolectadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorRecolectadoActionPerformed
        
    }//GEN-LAST:event_txtValorRecolectadoActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
// Leer el contenido de las cajas de texto
        String valorRecolectado = txtValorRecolectado.getText();
        String nombre = txtNombre.getText();
        String calidad = txtCalidad.getText();
        // Llevar los datos a los atributos del objeto a traves de las propiedades
        ingredientes.setValorRecolectado(valorRecolectado);
        ingredientes.setNombre(nombre);
        ingredientes.setCalidad(calidad);
        // Mostrar el mensaje de confirmación
        JOptionPane.showMessageDialog(rootPane,"Datos registrados en el objeto");    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Valor Recolectado: " + ingredientes.getValorRecolectado() + "\n" +
                                                "Nombre: " + ingredientes.getNombre() + "\n" +
                                                "Calidad: " + ingredientes.getCalidad() + "\n");    }//GEN-LAST:event_btnEscribirActionPerformed

    private void btnRecibirMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibirMonedaActionPerformed
        JOptionPane.showMessageDialog(rootPane, String.valueOf(ingredientes.RecibirMoneda().toString()));
    }//GEN-LAST:event_btnRecibirMonedaActionPerformed

    private void btnCancelarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarOperacionesActionPerformed
        JOptionPane.showMessageDialog(rootPane, String.valueOf(ingredientes.CancelarOperaciones().toString()));
    }//GEN-LAST:event_btnCancelarOperacionesActionPerformed

    private void btnServirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServirProductoActionPerformed
        JOptionPane.showMessageDialog(rootPane, String.valueOf(ingredientes.ServirProducto().toString()));
    }//GEN-LAST:event_btnServirProductoActionPerformed

    private void btnEntregarVueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarVueltoActionPerformed
        JOptionPane.showMessageDialog(rootPane, String.valueOf(ingredientes.EntregarVuelto().toString()));
    }//GEN-LAST:event_btnEntregarVueltoActionPerformed

    private void btnElegirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirIngredienteActionPerformed
        JOptionPane.showMessageDialog(rootPane, String.valueOf(ingredientes.ElegirIngrediente().toString()));
    }//GEN-LAST:event_btnElegirIngredienteActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarOperaciones;
    private javax.swing.JButton btnElegirIngrediente;
    private javax.swing.JButton btnEntregarVuelto;
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnRecibirMoneda;
    private javax.swing.JButton btnServirProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtValorRecolectado;
    // End of variables declaration//GEN-END:variables
}
